[package]
name = "phone_valid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "phone_valid"
path = "src/phone_valid.rs"

[dependencies]
regex = "1.10.5"
